///
///  BasicType.swift
///
///  Copyright 2017 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 10/8/17.
///
import Swift

/// =================================== NOTICE ========================================
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///
/// Modify the  *.swift.gyb file instead.
/// ===================================================================================

///
/// Type: `BasicClass`
///
/// Test type which represents a basic class used by a developer using the library.
///
public class BasicClass: Codable, EquatableType, CustomStringConvertible {
    public var boolVar: Bool
    public var intVar: Int
    public var doubleVar: Double
    public var stringVar: String

    public init(boolVar: Bool = false, intVar: Int = 0, doubleVar: Double = 0.00, stringVar: String = "") {
        self.boolVar   = boolVar
        self.intVar    = intVar
        self.doubleVar = doubleVar
        self.stringVar = stringVar
    }

    public func equals<T>(_ other: T) -> Bool where T: BasicClass {

        return self.boolVar   == other.boolVar &&
               self.intVar    == other.intVar &&
               self.doubleVar == other.doubleVar &&
               self.stringVar == other.stringVar
    }

    public static func == (lhs: BasicClass, rhs: BasicClass) -> Bool {
        return lhs.equals(rhs)
    }

    public var description: String {
        return "\(String(describing: type(of: self)))(boolVar: \(self.boolVar), intVar: \(self.intVar), doubleVar: \(self.doubleVar), stringVar: \"\(self.stringVar)\")"
    }
}

///
/// Type: `BasicStruct`
///
/// Test type which represents a basic struct used by a developer using the library.
///
public struct BasicStruct: Codable, EquatableType, CustomStringConvertible {
    public var boolVar: Bool
    public var intVar: Int
    public var doubleVar: Double
    public var stringVar: String

    public init(boolVar: Bool = false, intVar: Int = 0, doubleVar: Double = 0.00, stringVar: String = "") {
        self.boolVar   = boolVar
        self.intVar    = intVar
        self.doubleVar = doubleVar
        self.stringVar = stringVar
    }

    public func equals(_ other: BasicStruct) -> Bool {

        return self.boolVar   == other.boolVar &&
               self.intVar    == other.intVar &&
               self.doubleVar == other.doubleVar &&
               self.stringVar == other.stringVar
    }

    public static func == (lhs: BasicStruct, rhs: BasicStruct) -> Bool {
        return lhs.equals(rhs)
    }

    public var description: String {
        return "\(String(describing: type(of: self)))(boolVar: \(self.boolVar), intVar: \(self.intVar), doubleVar: \(self.doubleVar), stringVar: \"\(self.stringVar)\")"
    }
}

